### ISSUE TITLE
yarn and node versions are incompatible & Lambda runtime no longer supported

### ISSUE THREAD

**Issue by emolvera** [aws-samples/aws-serverless-auth-workshop#21]
I recently imparted this workshop and there ar a couple of changes that had to be made for it to work as expected:

1. yarn and node versions are incompatible 
In step **0. Setup: Setup Cloud9 Workspace**, during the Cloud9 setup, the final step is installing yarn. If the command `yarn install` is executed as is, this will throw the followig error: `The engine "node" is incompatible with this module.`
A workaround is to replace the command with `yarn install --ignore-engines`, as suggested in [StackOverflow](https://stackoverflow.com/questions/56617209/the-engine-node-is-incompatible-with-this-module)

2. Lambda runtime no longer supported
In step **2. Serverless API : Create Serverless API Backend**, the CloudFormation template `ServerlessBackend.yaml` is deployed. However, in line 58 of that template, the runtime `nodejs10.x` is specified, which is no longer supported by AWS Lambda. If the template is deployed as is, the stack will fail.
In order to solve this, within the YAML template replace `nodejs10.x` with a newer runtime supported by Lambda, for example `nodejs14.x`.

I suggest these changes are made to the workshop to keep other users from making the same mistakes when trying to run it.

**Comment by indranilbanerjee2014** [comment]
For the yarn start issue, I used the following workaround
Instead of
nvm i 10
nvm alias default 10
use
nvm i 12
nvm alias default 12

**Comment by cbmcpeek** [comment]
This has been resolved and now updated to node 16.
